name: Health check

on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  health_check:
   runs-on: ubuntu-18.04
   steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://luisnvrr-pokedex.herokuapp.com
        max-attempts: 2
        retry-delay: 5s